// Generated by ego.
// DO NOT EDIT

//line api\html\app.ego:1

package html

import "fmt"
import "html"
import "io"
import "context"

import (
	appUser "github.com/mmanjoura/template/user"
	"github.com/mmanjoura/template/api/assets"
)

// MeasurementID is a Google Analytics measurement ID.
// It has to be set globally so we can avoid passing it to every template.
var MeasurementID string

type App struct {
	Title      string
	Chromeless bool

	Header func()
	Footer func()

	Yield func()
}

func (app *App) Render(ctx context.Context, w io.Writer) {
	user := appUser.UserFromContext(ctx)

//line api\html\app.ego:26
	_, _ = io.WriteString(w, "\n<!DOCTYPE html>\n\n<html dir=\"ltr\" lang=\"en-US\">\n<head>\n\t<meta charset=\"utf-8\">\n\t<meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\">\n\t<meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\n\n\t<title>\n\t\t")
//line api\html\app.ego:35
	if app.Title != "" {
//line api\html\app.ego:36
		_, _ = io.WriteString(w, "\n\t\t\t")
//line api\html\app.ego:36
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(app.Title)))
//line api\html\app.ego:37
		_, _ = io.WriteString(w, "\n\t\t")
//line api\html\app.ego:37
	} else {
//line api\html\app.ego:38
		_, _ = io.WriteString(w, "\n\t\t\tWTF Dial\n\t\t")
//line api\html\app.ego:39
	}
//line api\html\app.ego:40
	_, _ = io.WriteString(w, "\n\t</title>\n\n\n\t")
//line api\html\app.ego:43
	if HasTheme {
//line api\html\app.ego:44
		_, _ = io.WriteString(w, "\n\t\t<link href=\"/assets/")
//line api\html\app.ego:44
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(assets.FS.HashName(ThemePath))))
//line api\html\app.ego:44
		_, _ = io.WriteString(w, "\" rel=\"stylesheet\" />\n\t")
//line api\html\app.ego:45
	} else {
//line api\html\app.ego:46
		_, _ = io.WriteString(w, "\n\t\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n\t")
//line api\html\app.ego:47
	}
//line api\html\app.ego:48
	_, _ = io.WriteString(w, "\n\t<link href=\"/assets/")
//line api\html\app.ego:48
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(assets.FS.HashName(`css/fontawesome.css`))))
//line api\html\app.ego:48
	_, _ = io.WriteString(w, "\" rel=\"stylesheet\" />\n\n\t")
//line api\html\app.ego:50
	if MeasurementID != "" {
//line api\html\app.ego:51
		_, _ = io.WriteString(w, "\n\t\t<script async src=\"https://www.googletagmanager.com/gtag/js?id=")
//line api\html\app.ego:51
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(MeasurementID)))
//line api\html\app.ego:51
		_, _ = io.WriteString(w, "\"></script>\n\t\t<script>\n\t\t\twindow.dataLayer = window.dataLayer || [];\n\t\t\tfunction gtag(){dataLayer.push(arguments);}\n\t\t\tgtag('js', new Date());\n\t\t\tgtag('config', '")
//line api\html\app.ego:56
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(MeasurementID)))
//line api\html\app.ego:56
		_, _ = io.WriteString(w, "');\n\t\t</script>\n\t")
//line api\html\app.ego:58
	}
//line api\html\app.ego:59
	_, _ = io.WriteString(w, "\n\t")
//line api\html\app.ego:59
	if app.Header != nil {
//line api\html\app.ego:59
		app.Header()
//line api\html\app.ego:59
	}
//line api\html\app.ego:60
	_, _ = io.WriteString(w, "\n</head>\n\n<body>\n\t")
//line api\html\app.ego:63
	if app.Chromeless {
//line api\html\app.ego:64
		_, _ = io.WriteString(w, "\n\t\t")
//line api\html\app.ego:64
		if app.Yield != nil {
//line api\html\app.ego:64
			app.Yield()
//line api\html\app.ego:64
		}
//line api\html\app.ego:65
		_, _ = io.WriteString(w, "\n\t")
//line api\html\app.ego:65
	} else {
//line api\html\app.ego:66
		_, _ = io.WriteString(w, "\n\t\t<main class=\"main\" id=\"top\">\n\t\t\t<div class=\"container\" data-layout=\"container\">\n\t\t\t\t<nav class=\"navbar navbar-light navbar-top navbar-glass navbar-expand-md\">\n\t\t\t\t\t<button aria-controls=\"navbar\" aria-expanded=\"false\" aria-label=\"Toggle Navigation\" class=\"btn navbar-toggler-humburger-icon navbar-toggler mr-1 mr-sm-3\" data-target=\"#navbar\" data-toggle=\"collapse\" type=\"button\">\n\t\t\t\t\t\t<span class=\"navbar-toggle-icon\">\n\t\t\t\t\t\t\t<span class=\"toggle-line\"></span>\n\t\t\t\t\t\t</span>\n\t\t\t\t\t</button>\n\n\t\t\t\t\t<a class=\"navbar-brand mr-1 mr-sm-3\" href=\"/\">\n\t\t\t\t\t\t<span class=\"font-sans-serif\">WTF Dial</span>\n\t\t\t\t\t</a>\n\n\t\t\t\t\t<div class=\"collapse navbar-collapse scrollbar\" id=\"navbar\">\n\t\t\t\t\t\t<ul class=\"navbar-nav\">\n\t\t\t\t\t\t\t<li class=\"nav-item\">\n\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/\" role=\"button\">\n\t\t\t\t\t\t\t\t\tDashboard\n\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t<li class=\"nav-item dropdown\">\n\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/dials\" role=\"button\">\n\t\t\t\t\t\t\t\t\tMy Dials\n\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t</div>\n\n\t\t\t\t\t<ul class=\"navbar-nav navbar-nav-icons ml-auto flex-row align-items-center\">\n\t\t\t\t\t\t")
//line api\html\app.ego:96
		if user != nil {
//line api\html\app.ego:97
			_, _ = io.WriteString(w, "\n\t\t\t\t\t\t\t<li class=\"nav-item dropdown\">\n\t\t\t\t\t\t\t\t<a aria-expanded=\"false\" aria-haspopup=\"true\" class=\"nav-link pr-0\" data-toggle=\"dropdown\" href=\"#\" id=\"avatarDropdown\" role=\"button\">\n\t\t\t\t\t\t\t\t\t<div class=\"avatar avatar-xl\">\n\t\t\t\t\t\t\t\t\t\t<img alt=\"\" class=\"rounded-circle\" src=\"")
//line api\html\app.ego:100
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(user.AvatarURL(100))))
//line api\html\app.ego:100
			_, _ = io.WriteString(w, "\">\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</a>\n\n\t\t\t\t\t\t\t\t<div aria-labelledby=\"avatarDropdown\" class=\"dropdown-menu dropdown-menu-right py-0\">\n\t\t\t\t\t\t\t\t\t<div class=\"bg-white rounded-lg py-2\">\n\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/settings\">\n\t\t\t\t\t\t\t\t\t\t\tSettings\n\t\t\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t\t\t\t<button class=\"dropdown-item\" type=\"submit\" form=\"logoutForm\">\n\t\t\t\t\t\t\t\t\t\t\tLogout\n\t\t\t\t\t\t\t\t\t\t</button>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t")
//line api\html\app.ego:115
		}
//line api\html\app.ego:116
		_, _ = io.WriteString(w, "\n\t\t\t\t\t</ul>\n\t\t\t\t</nav>\n\n\t\t\t\t")
//line api\html\app.ego:119
		if app.Yield != nil {
//line api\html\app.ego:119
			app.Yield()
//line api\html\app.ego:119
		}
//line api\html\app.ego:120
		_, _ = io.WriteString(w, "\n\t\t\t</div>\n\t\t</main>\n\n\t\t<form id=\"logoutForm\" action=\"/logout\" method=\"POST\">\n\t\t\t<input type=\"hidden\" name=\"_method\" value=\"DELETE\"/>\n\t\t</form>\n\t")
//line api\html\app.ego:126
	}
//line api\html\app.ego:127
	_, _ = io.WriteString(w, "\n\n\t<footer></footer>\n\t\n\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.min.js\" integrity=\"sha256-7YDdEJPH+l7DKZyVWiQSAVM6X7h0P9OTs18HzyNSCPY=\" crossorigin=\"anonymous\"></script>\n\t<script src=\"https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.js\" integrity=\"sha256-8AdWdyRXkrETyAGla9NmgkYVlqw4MOHR6sJJmtFGAYQ=\" crossorigin=\"anonymous\"></script>\n\t<script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js\" integrity=\"sha256-t9UJPrESBeG2ojKTIcFLPGF7nHi2vEc7f5A2KpH/UBU=\" crossorigin=\"anonymous\"></script>\n\t<script src=\"/assets/")
//line api\html\app.ego:133
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(assets.FS.HashName(`scripts/reconnecting-websocket.js`))))
//line api\html\app.ego:133
	_, _ = io.WriteString(w, "\"></script>\n\t<script src=\"/assets/")
//line api\html\app.ego:134
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(assets.FS.HashName(`scripts/main.js`))))
//line api\html\app.ego:134
	_, _ = io.WriteString(w, "\"></script>\n\t<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700%7cPoppins:100,200,300,400,500,600,700,800,900&amp;display=swap\" rel=\"stylesheet\">\n\t\n\t")
//line api\html\app.ego:137
	if app.Footer != nil {
//line api\html\app.ego:137
		app.Footer()
//line api\html\app.ego:137
	}
//line api\html\app.ego:138
	_, _ = io.WriteString(w, "\n</body>\n</html>\n")
//line api\html\app.ego:140
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
