// Generated by ego.
// DO NOT EDIT

//line api\html\login.ego:1

package html

import "fmt"
import "html"
import "io"
import "context"

type LoginTemplate struct{}

func (tmpl *LoginTemplate) Render(ctx context.Context, w io.Writer) {

//line api\html\login.ego:7
	{
		var EGO App
		EGO.Title = "Log in"
		EGO.Chromeless = true
		EGO.Yield = func() {
//line api\html\login.ego:8
			_, _ = io.WriteString(w, "\n<main class=\"main\" id=\"top\">\n\t<div class=\"container\" data-layout=\"container\">\n\t\t<div class=\"row flex-center py-6\">\n\t\t\t<div class=\"col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4\">\n\t\t\t\t<a class=\"d-flex flex-center mb-4\" href=\"/\">\n\t\t\t\t\t<span class=\"font-sans-serif font-weight-bolder fs-5 d-inline-block\">\n\t\t\t\t\t\tWTF Dial\n\t\t\t\t\t</span>\n\t\t\t\t</a>\n\n\t\t\t\t<div class=\"card\">\n\t\t\t\t\t<div class=\"card-body p-4 pt-2 p-sm-5 pt-sm-3\">\n\t\t\t\t\t\t<div class=\"position-relative mt-4\">\n\t\t\t\t\t\t\t<hr class=\"bg-300\">\n\t\t\t\t\t\t\t<div class=\"position-absolute top-50 left-50 translate-middle px-3 bg-white font-sans-serif fs--1 text-500 text-nowrap\">\n\t\t\t\t\t\t\t\tLog in with\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t<div class=\"row g-2 mt-2\">\n\t\t\t\t\t\t\t<div class=\"col\">\n\t\t\t\t\t\t\t\t<a class=\"btn btn-outline-dark btn-block\" href=\"/oauth/github\">\n\t\t\t\t\t\t\t\t\t<i class=\"fab fa-github mr-1\"></i>\n\t\t\t\t\t\t\t\t\tGitHub\n\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</main>\n")
		}
		EGO.Render(ctx, w)
	}
//line api\html\login.ego:41
	_, _ = io.WriteString(w, "\n")
//line api\html\login.ego:41
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
